/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as TDShape from "../TDShape.js";
import type * as clear from "../clear.js";
import type * as getPresence from "../getPresence.js";
import type * as getRoom from "../getRoom.js";
import type * as storage from "../storage.js";
import type * as updatePresence from "../updatePresence.js";
import type * as updateRoom from "../updateRoom.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  TDShape: typeof TDShape;
  clear: typeof clear;
  getPresence: typeof getPresence;
  getRoom: typeof getRoom;
  storage: typeof storage;
  updatePresence: typeof updatePresence;
  updateRoom: typeof updateRoom;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
